# Generated by Django 3.1.2 on 2020-11-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_auto_20201125_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
